workflows:
  geomaster-release:
    name: GeoMaster Release Build
    max_build_duration: 60

    environment:
      flutter: stable
      java: 17

    scripts:
      - name: Clean and get packages
        script: |
          flutter clean
          flutter pub get

      - name: Build GeoMaster (.AAB + .APK)
        script: |
          flutter build appbundle --release
          flutter build apk --release

      - name: Fix Codemagic artifact paths
        script: |
          echo "Searching for AAB..."
          find build/ -name "*.aab"

          echo "Searching for APK..."
          find build/ -name "*.apk"

    artifacts:
      - build/**/**/*.aab
      - build/**/**/*.apk
