workflows:
  geomaster-release:
    name: GeoMaster Release Build
    max_build_duration: 90

    environment:
      flutter: stable
      java: 17

    scripts:
      - name: Clean & get packages
        script: |
          flutter clean
          flutter pub get

      - name: Build Android with Gradle (release)
        script: |
          cd android
          ./gradlew clean
          ./gradlew bundleRelease assembleRelease

    artifacts:
      - android/app/build/outputs/**/*.aab
      - android/app/build/outputs/**/*.apk
